### ISSUE TITLE
Android Basics: Lemonade app

### ISSUE THREAD

**Issue by xionous** [google-developer-training/android-basics-kotlin-lemonade-app#52]
Hello,

When I try to run the tests no matter which test I run I get this error:

```
11-18 17:37:17.552  8725  8746 E TestRunner: ----- begin exception -----
11-18 17:37:17.553  8725  8746 E TestRunner: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.lemonade.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
11-18 17:37:17.553  8725  8746 E TestRunner: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2158)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.runner.MonitoringInstrumentation.execStartActivity(MonitoringInstrumentation.java:564)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:454)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:431)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:437)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at com.example.lemonade.LemonadeTests.setup(LemonadeTests.kt:120)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
11-18 17:37:17.553  8725  8746 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2322)
11-18 17:37:17.553  8725  8746 E TestRunner: ----- end exception -----
```

I have tried to search on google but I have not been able to find and answer as to what is causing this. Can someone help me figure this out?

When I run the app itself everything seems to work as it should it is just the tests that do not work.

**Comment by Jerrot** [comment]
It's a known bug with Android 13 within the version of core-ctx that is used in this project. To fix it, open your build.gradle (Module: Lemonade.app) and find the corresponding dependency in line 57.

Change the version to 1.5.0 (as of today) like this:
`androidTestImplementation "androidx.test:core-ktx:1.5.0"`

**Comment by xionous** [comment]
Thank you for your help @Jerrot , that was it!

![image](https://user-images.githubusercontent.com/813461/202887366-1bc6915d-d9b9-4564-8f73-7843d7d28ee0.png)

**Comment by mostafaSamir33** [comment]
@xionous may you put lemonade app on githup or send it to me if you can because i can't move from a state to another and searched for a long time but didn't get the answer
